"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.PathNiceWin32 = exports.pathWin32 = exports.PathNicePosix = exports.pathPosix = exports.ParsedPathNice = exports.PathNice = exports.path = void 0;
const path_js_1 = require("./auto/path.js");
Object.defineProperty(exports, "path", { enumerable: true, get: function () { return path_js_1.path; } });
Object.defineProperty(exports, "PathNice", { enumerable: true, get: function () { return path_js_1.PathNice; } });
Object.defineProperty(exports, "ParsedPathNice", { enumerable: true, get: function () { return path_js_1.ParsedPathNice; } });
const path_js_2 = require("./posix/path.js");
Object.defineProperty(exports, "pathPosix", { enumerable: true, get: function () { return path_js_2.pathPosix; } });
Object.defineProperty(exports, "PathNicePosix", { enumerable: true, get: function () { return path_js_2.PathNicePosix; } });
const path_js_3 = require("./win32/path.js");
Object.defineProperty(exports, "pathWin32", { enumerable: true, get: function () { return path_js_3.pathWin32; } });
Object.defineProperty(exports, "PathNiceWin32", { enumerable: true, get: function () { return path_js_3.PathNiceWin32; } });
path_js_1.path.posix = path_js_2.pathPosix;
path_js_1.path.win32 = path_js_3.pathWin32;
path_js_1.path.PathNice = path_js_1.PathNice;
path_js_1.path.PathNicePosix = path_js_2.PathNicePosix;
path_js_1.path.PathNiceWin32 = path_js_3.PathNiceWin32;
path_js_2.pathPosix.posix = path_js_2.pathPosix;
path_js_2.pathPosix.win32 = path_js_3.pathWin32;
path_js_2.pathPosix.PathNice = path_js_1.PathNice;
path_js_2.pathPosix.PathNicePosix = path_js_2.PathNicePosix;
path_js_2.pathPosix.PathNiceWin32 = path_js_3.PathNiceWin32;
path_js_3.pathWin32.posix = path_js_2.pathPosix;
path_js_3.pathWin32.win32 = path_js_3.pathWin32;
path_js_3.pathWin32.PathNice = path_js_1.PathNice;
path_js_3.pathWin32.PathNicePosix = path_js_2.PathNicePosix;
path_js_3.pathWin32.PathNiceWin32 = path_js_3.PathNiceWin32;
//# sourceMappingURL=path.js.map