import { path, Path } from './path.js';

export default path;

export type FileSystem = Path.FileSystem;
/**
 * A parsed path object generated by path.parse() or consumed by path.format().
 */
export interface ParsedPath extends Path.ParsedPath {}
export interface FormatInputPathObject extends Path.FormatInputPathObject {}
export interface PlatformPath extends Path.PlatformPath { }

// prettier-ignore
const {
    delimiter, sep, posix, win32,
    basename, dirname, extname, format, isAbsolute, join, normalize, parse,
    relative, resolve, toNamespacedPath,
} = path;

// prettier-ignore
export {
    delimiter, sep, posix, win32,
    basename, dirname, extname, format, isAbsolute, join, normalize, parse,
    relative, resolve, toNamespacedPath,
};
